/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Asus
 */
public class dataDonatur extends javax.swing.JFrame {
    private Connection con = new koneksi().connect();
    private Statement stat;
    private ResultSet res;
    private DefaultTableModel tabmode;

    /**
     * Creates new form dataDonatur
     */
    public dataDonatur() {
        initComponents();
        datatable();
        setLocationRelativeTo(this);
    }
    
    protected void aktif(){
        tId.setEnabled(true);
        tNama.setEnabled(true);
        tNo.setEnabled(true);
        rPr.setEnabled(true);
        rLk.setEnabled(true);
        tLahir.setEnabled(true);
        tAlamat.setEnabled(true);
        tCari.setEnabled(true);
        tId.requestFocus();
    }
    
    protected void kosong() {
        tId.setText("");
        tNama.setText("");
        tNo.setText("");
        buttonGroup1.clearSelection();
        tLahir.setText("");
        tAlamat.setText("");
    }
    
    protected void datatable() {
        Object[] Baris={"ID Donatur","Nama Lengkap","No HP","Jenis Kelamin","Tanggal Lahir","Alamat"};
        tabmode=new DefaultTableModel(null,Baris);
        tabelDonatur.setModel(tabmode);
        String sql="SELECT * FROM donatur";
        
        try{
            java.sql.Statement stat=con.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("idDonatur");
                String b = hasil.getString("namaDonatur");
                String c = hasil.getString("noHp");
                String d = hasil.getString("jk");
                String e = hasil.getString("ttl");
                String f = hasil.getString("alamat");
            
                String[] data={a,b,c,d,e,f};
                tabmode.addRow(data);
            }
        }catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnMenu = new javax.swing.JButton();
        btnDonatur = new javax.swing.JButton();
        btnPengelola = new javax.swing.JButton();
        btnSantri = new javax.swing.JButton();
        btnDana = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnPengeluaran = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        Lform = new javax.swing.JLabel();
        idDonatur = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        namaLengkap = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        noHp = new javax.swing.JLabel();
        tNo = new javax.swing.JTextField();
        jenisKelamin = new javax.swing.JLabel();
        rLk = new javax.swing.JRadioButton();
        rPr = new javax.swing.JRadioButton();
        tglLahir = new javax.swing.JLabel();
        tLahir = new javax.swing.JTextField();
        alamat = new javax.swing.JLabel();
        tAlamat = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKosong = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        data = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDonatur = new javax.swing.JTable();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(914, 850));
        setMinimumSize(new java.awt.Dimension(914, 690));
        setPreferredSize(new java.awt.Dimension(914, 650));
        setSize(new java.awt.Dimension(914, 650));
        getContentPane().setLayout(null);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnMenu.png"))); // NOI18N
        btnMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(0, 60, 170, 50);

        btnDonatur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - bold - btnDonatur.png"))); // NOI18N
        btnDonatur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDonatur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonaturActionPerformed(evt);
            }
        });
        getContentPane().add(btnDonatur);
        btnDonatur.setBounds(0, 110, 170, 50);

        btnPengelola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnPengelola.png"))); // NOI18N
        btnPengelola.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPengelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengelolaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengelola);
        btnPengelola.setBounds(0, 160, 170, 50);

        btnSantri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnSantri.png"))); // NOI18N
        btnSantri.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSantri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSantriActionPerformed(evt);
            }
        });
        getContentPane().add(btnSantri);
        btnSantri.setBounds(0, 210, 170, 50);

        btnDana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnDana.png"))); // NOI18N
        btnDana.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDana);
        btnDana.setBounds(0, 260, 170, 50);

        btnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnBarang.png"))); // NOI18N
        btnBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnBarang);
        btnBarang.setBounds(0, 310, 170, 50);

        btnPengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnPengeluaran.png"))); // NOI18N
        btnPengeluaran.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengeluaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengeluaran);
        btnPengeluaran.setBounds(0, 360, 170, 50);

        Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Keluar.png"))); // NOI18N
        Keluar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(10, 590, 150, 40);

        Lform.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Lform.setText("Form Data Donatur");
        getContentPane().add(Lform);
        Lform.setBounds(190, 80, 170, 20);

        idDonatur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idDonatur.setText("ID Donatur");
        getContentPane().add(idDonatur);
        idDonatur.setBounds(230, 110, 110, 17);

        tId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tId);
        tId.setBounds(400, 100, 290, 30);

        namaLengkap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaLengkap.setText("Nama Lengkap");
        getContentPane().add(namaLengkap);
        namaLengkap.setBounds(230, 150, 110, 17);

        tNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tNama);
        tNama.setBounds(400, 140, 290, 30);

        noHp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noHp.setText("No Hp");
        getContentPane().add(noHp);
        noHp.setBounds(230, 190, 110, 17);

        tNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tNo);
        tNo.setBounds(400, 180, 290, 30);

        jenisKelamin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jenisKelamin.setText("Jenis Kelamin");
        getContentPane().add(jenisKelamin);
        jenisKelamin.setBounds(230, 230, 110, 17);

        rLk.setBackground(new java.awt.Color(194, 194, 194));
        buttonGroup1.add(rLk);
        rLk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rLk.setText("Laki - Laki");
        rLk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLkActionPerformed(evt);
            }
        });
        getContentPane().add(rLk);
        rLk.setBounds(400, 220, 100, 30);

        rPr.setBackground(new java.awt.Color(194, 194, 194));
        buttonGroup1.add(rPr);
        rPr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rPr.setText("Perempuan");
        rPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPrActionPerformed(evt);
            }
        });
        getContentPane().add(rPr);
        rPr.setBounds(500, 220, 160, 30);

        tglLahir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tglLahir.setText("Tempat, Tanggal Lahir");
        getContentPane().add(tglLahir);
        tglLahir.setBounds(230, 270, 150, 17);

        tLahir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tLahir);
        tLahir.setBounds(400, 260, 290, 30);

        alamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alamat.setText("Alamat");
        getContentPane().add(alamat);
        alamat.setBounds(230, 310, 110, 17);

        tAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tAlamat);
        tAlamat.setBounds(400, 300, 290, 60);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Simpan.png"))); // NOI18N
        btnSimpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(750, 100, 100, 40);

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn ubah.png"))); // NOI18N
        btnUbah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah);
        btnUbah.setBounds(750, 160, 100, 40);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Hapus.png"))); // NOI18N
        btnHapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus);
        btnHapus.setBounds(750, 220, 100, 40);

        btnKosong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Kosong.png"))); // NOI18N
        btnKosong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });
        getContentPane().add(btnKosong);
        btnKosong.setBounds(750, 280, 100, 40);

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cetak.png"))); // NOI18N
        btnCetak.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak);
        btnCetak.setBounds(750, 340, 100, 40);

        data.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        data.setText("Data Donatur");
        getContentPane().add(data);
        data.setBounds(200, 380, 130, 20);

        tCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCariKeyPressed(evt);
            }
        });
        getContentPane().add(tCari);
        tCari.setBounds(580, 410, 240, 30);

        btnCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnCari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari);
        btnCari.setBounds(830, 410, 40, 30);

        tabelDonatur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Donatur", "Nama Lengkap", "No HP", "Jenis Kelamin", "Tanggal Lahir", "Alamat"
            }
        ));
        tabelDonatur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDonaturMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDonatur);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 450, 680, 190);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/T_DONATUR.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 914, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        new beranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnDonaturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonaturActionPerformed
        // TODO add your handling code here:
        new dataDonatur().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDonaturActionPerformed

    private void btnPengelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengelolaActionPerformed
        // TODO add your handling code here:
        new dataPengelola().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPengelolaActionPerformed

    private void btnSantriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSantriActionPerformed
        // TODO add your handling code here:
        new dataSantri().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSantriActionPerformed

    private void btnDanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanaActionPerformed
        // TODO add your handling code here:
        new masukDana().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDanaActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        new masukBarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengeluaranActionPerformed
        // TODO add your handling code here:
        new pengeluaran().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPengeluaranActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    private void rPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rPrActionPerformed

    private void rLkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rLkActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="UPDATE donatur set IdDonatur=?, namaDonatur=?, noHp=?, jk=?, "
                    + "ttl=?, alamat=? Where IdDonatur =  '"+tId.getText()+"'";
            PreparedStatement stat = con.prepareStatement(sql);       
            stat.setString(1, tId.getText());
            stat.setString(2, tNama.getText());
            stat.setString(3, tNo.getText());
            String jk = "";
                if(rLk.isSelected()) jk = "Laki - Laki";
                else jk = "Perempuan";
            stat.setString(4, jk);
            stat.setString(5, tLahir.getText());
            stat.setString(6, tAlamat.getText());
         
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil di Ubah");  
            kosong();
            tCari.requestFocus();
            datatable();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Gagal di Ubah "+e); 
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO donatur values(?,?,?,?,?,?)";
        try {
            PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, tId.getText());
            stat.setString(2, tNama.getText());
            stat.setString(3, tNo.getText());
            String jk = "";
                if(rLk.isSelected()) jk = "Laki - Laki";
                else jk = "Perempuan";
            stat.setString(4, jk);
            stat.setString(5, tLahir.getText());
            stat.setString(6, tAlamat.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan");
            kosong();
            tCari.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Simpan"+e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int hapus = JOptionPane.showConfirmDialog(null,"Hapus", "Konfirmasi Dialog", 
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(hapus == 0) {
            String sql="DELETE FROM donatur Where IdDonatur =  '"+tId.getText()+"'";
            try {
                PreparedStatement stat = con.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
                kosong();
                tCari.requestFocus();
                datatable();
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Data Gagal di Hapus"+e);
            }  
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        JasperReport reports;
        String path = "C:\\Users\\user\\Documents\\NetBeansProjects\\aplikasi_donatur\\src\\cetakan\\report_donatur.jasper";
        
        try {
            HashMap hash = new HashMap();
            String inputId = JOptionPane.showInputDialog("Masukkan Id Donatur:");
            hash.put("id_donatur", inputId);
            
            reports = (JasperReport) net.sf.jasperreports.engine.util.JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, hash, con);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(masukDana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void tabelDonaturMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDonaturMouseClicked
        // TODO add your handling code here:
        int bar = tabelDonatur.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        
        tId.setText(a);
        tNama.setText(b);
        tNo.setText(c);
        if(d.equals("Laki - Laki")){
            rLk.setSelected(true); 
            rPr.setSelected(false);
        }else {
            rLk.setSelected(false); 
            rPr.setSelected(true);
        }
        tLahir.setText(e);
        tAlamat.setText(f);
    }//GEN-LAST:event_tabelDonaturMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        Object[] Baris={"ID Donatur","Nama Lengkap","No HP","Jenis Kelamin","Tanggal Lahir","Alamat"};
        tabmode=new DefaultTableModel(null,Baris);
        tabelDonatur.setModel(tabmode);
        String sql="SELECT * FROM donatur WHERE idDonatur LIKE '%"+tCari.getText()+"%'";
        
        try{
            java.sql.Statement stat=con.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("idDonatur");
                String b = hasil.getString("namaDonatur");
                String c = hasil.getString("noHp");
                String d = hasil.getString("jk");
                String e = hasil.getString("ttl");
                String f = hasil.getString("alamat");
            
                String[] data={a,b,c,d,e,f};
                tabmode.addRow(data);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Data tidak ditemukan"+e);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void tCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyPressed
        // TODO add your handling code here:
//       Object[] Baris={"ID Donatur","Nama Lengkap","No HP","Jenis Kelamin","Tanggal Lahir","Alamat"};
//        tabmode=new DefaultTableModel(null,Baris);
//        tabelDonatur.setModel(tabmode);
//        String sql="SELECT * FROM donatur WHERE idDonatur LIKE '%"+tCari.getText()+"%'";
//        
//        try{
//            java.sql.Statement stat=con.createStatement();
//            ResultSet hasil=stat.executeQuery(sql);
//            while(hasil.next()){
//                String a = hasil.getString("idDonatur");
//                String b = hasil.getString("namaDonatur");
//                String c = hasil.getString("noHp");
//                String d = hasil.getString("jk");
//                String e = hasil.getString("ttl");
//                String f = hasil.getString("alamat");
//            
//                String[] data={a,b,c,d,e,f};
//                tabmode.addRow(data);
//            }
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null,"Data tidak ditemukan"+e);
//        }
    }//GEN-LAST:event_tCariKeyPressed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnKosongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataDonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataDonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataDonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataDonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataDonatur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel Lform;
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnDana;
    private javax.swing.JButton btnDonatur;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKosong;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPengelola;
    private javax.swing.JButton btnPengeluaran;
    private javax.swing.JButton btnSantri;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel data;
    private javax.swing.JLabel idDonatur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenisKelamin;
    private javax.swing.JLabel namaLengkap;
    private javax.swing.JLabel noHp;
    private javax.swing.JRadioButton rLk;
    private javax.swing.JRadioButton rPr;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tLahir;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNo;
    private javax.swing.JTable tabelDonatur;
    private javax.swing.JLabel tglLahir;
    // End of variables declaration//GEN-END:variables
}
