/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class login extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        koneksi();
        setLocationRelativeTo(this);
    }
    
    private void koneksi(){
       try{
           Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://localhost/db_dataqu", "root", "");
           stat=con.createStatement();
       } catch (ClassNotFoundException | SQLException e){
           JOptionPane.showMessageDialog(null, e);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKeluar = new javax.swing.JButton();
        btnMasuk = new javax.swing.JButton();
        tPassword = new javax.swing.JPasswordField();
        tNamaPengguna = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(914, 850));
        setMinimumSize(new java.awt.Dimension(914, 690));
        setPreferredSize(new java.awt.Dimension(914, 650));
        setSize(new java.awt.Dimension(914, 650));
        getContentPane().setLayout(null);

        btnKeluar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(700, 460, 140, 40);

        btnMasuk.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnMasuk.setText("MASUK");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        getContentPane().add(btnMasuk);
        btnMasuk.setBounds(520, 460, 140, 40);

        tPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tPassword);
        tPassword.setBounds(520, 370, 310, 40);

        tNamaPengguna.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tNamaPengguna.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tNamaPengguna);
        tNamaPengguna.setBounds(520, 260, 310, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/T_LOGIN.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 914, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Statement stat = con.createStatement();
            ResultSet result=stat.executeQuery ("select * from pengguna where "
                + "user='" +tNamaPengguna.getText()+"'");
            if (result.next()) {
                if (tPassword.getText().equals(result.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Login Berhasil");
                    new beranda().setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane,"Password Salah");
                    tPassword.setText("");
                    tNamaPengguna.requestFocus();
                }} else {
                    JOptionPane.showMessageDialog(rootPane, "User Tidak Ditemukan");
                    tNamaPengguna.setText("");
                    tPassword.setText("");
                    tNamaPengguna.requestFocus();
                }
            } catch (Exception e){
                JOptionPane.showMessageDialog(rootPane, "Gagal");
            }
    }//GEN-LAST:event_btnMasukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JTextField tNamaPengguna;
    private javax.swing.JPasswordField tPassword;
    // End of variables declaration//GEN-END:variables
}
