/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.util.JRLoader;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Asus
 */
public class masukBarang extends javax.swing.JFrame {
    private Connection con = new koneksi().connect();
    private Statement stat;
    private ResultSet res;
    private DefaultTableModel tabmode;

    /**
     * Creates new form masukBarang
     */
    public masukBarang() {
        initComponents();
        datatable();
        setLocationRelativeTo(this);
    }
    
    protected void aktif(){
        tIdBarang.setEnabled(true);
        tTgl.setEnabled(true);
        tIdDonatur.setEnabled(true);
        tNamaDonatur.setEnabled(true);
        tIdPengelola.setEnabled(true);
        tNamaPengelola.setEnabled(true);
        cbJenis.setEnabled(true);
        tJumlah.setEnabled(true);
        tKeterangan.setEnabled(true);
        tIdBarang.requestFocus();
    }
    
    protected void kosong() {
        tIdBarang.setText("");
        tTgl.setText("");
        tIdDonatur.setText("");
        tNamaDonatur.setText("");
        tIdPengelola.setText("");
        tNamaPengelola.setText("");
        cbJenis.setSelectedItem("");
        tJumlah.setText("");
        tKeterangan.setText("");
    }

    protected void datatable() {
        Object[] Baris={"ID Barang","Tanggal Barang diterima","ID Donatur","Nama Donatur",
            "ID Pengelola","Nama Pengelola","Jenis","Jumlah","Keterangan"};
        tabmode=new DefaultTableModel(null,Baris);
        tabelBarang.setModel(tabmode);
        String sql="SELECT * FROM barang";
        
        try{
            java.sql.Statement stat=con.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("idBarang");
                String b = hasil.getString("tgl");
                String c = hasil.getString("idDonatur");
                String d = hasil.getString("namaDonatur");
                String e = hasil.getString("idPengelola");
                String f = hasil.getString("namaPengelola");
                String g = hasil.getString("jenisBarang");
                String h = hasil.getString("jumlahBarang");
                String i = hasil.getString("keterangan");
            
                String[] data={a,b,c,d,e,f,g,h,i};
                tabmode.addRow(data);
            }
        }catch(Exception e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        btnDonatur = new javax.swing.JButton();
        btnPengelola = new javax.swing.JButton();
        btnSantri = new javax.swing.JButton();
        btnDana = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnPengeluaran = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        idBarang = new javax.swing.JLabel();
        tIdBarang = new javax.swing.JTextField();
        tglMasuk = new javax.swing.JLabel();
        tTgl = new javax.swing.JTextField();
        idDonatur = new javax.swing.JLabel();
        tIdDonatur = new javax.swing.JTextField();
        namaDonatur = new javax.swing.JLabel();
        tNamaDonatur = new javax.swing.JTextField();
        idPengelola = new javax.swing.JLabel();
        tIdPengelola = new javax.swing.JTextField();
        namaPengelola = new javax.swing.JLabel();
        tNamaPengelola = new javax.swing.JTextField();
        Jenis = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox<>();
        jumlah = new javax.swing.JLabel();
        tJumlah = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();
        tKeterangan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        btnCari = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();
        data = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKosong = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(914, 850));
        setMinimumSize(new java.awt.Dimension(914, 690));
        setPreferredSize(new java.awt.Dimension(914, 650));
        getContentPane().setLayout(null);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnMenu.png"))); // NOI18N
        btnMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(0, 60, 170, 50);

        btnDonatur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnDonatur.png"))); // NOI18N
        btnDonatur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDonatur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonaturActionPerformed(evt);
            }
        });
        getContentPane().add(btnDonatur);
        btnDonatur.setBounds(0, 110, 170, 50);

        btnPengelola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnPengelola.png"))); // NOI18N
        btnPengelola.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPengelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengelolaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengelola);
        btnPengelola.setBounds(0, 160, 170, 50);

        btnSantri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnSantri.png"))); // NOI18N
        btnSantri.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSantri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSantriActionPerformed(evt);
            }
        });
        getContentPane().add(btnSantri);
        btnSantri.setBounds(0, 210, 170, 50);

        btnDana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnDana.png"))); // NOI18N
        btnDana.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDana);
        btnDana.setBounds(0, 260, 170, 50);

        btnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - bold - btnBarang.png"))); // NOI18N
        btnBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnBarang);
        btnBarang.setBounds(0, 310, 170, 50);

        btnPengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnPengeluaran.png"))); // NOI18N
        btnPengeluaran.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengeluaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengeluaran);
        btnPengeluaran.setBounds(0, 360, 170, 50);

        Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Keluar.png"))); // NOI18N
        Keluar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(10, 570, 150, 40);

        idBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idBarang.setText("ID Barang Masuk");
        getContentPane().add(idBarang);
        idBarang.setBounds(190, 90, 130, 17);

        tIdBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tIdBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdBarangActionPerformed(evt);
            }
        });
        getContentPane().add(tIdBarang);
        tIdBarang.setBounds(310, 80, 190, 30);

        tglMasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tglMasuk.setText("Tanggal diterima");
        getContentPane().add(tglMasuk);
        tglMasuk.setBounds(190, 130, 130, 17);

        tTgl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTglActionPerformed(evt);
            }
        });
        getContentPane().add(tTgl);
        tTgl.setBounds(310, 120, 190, 30);

        idDonatur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idDonatur.setText("ID Donatur");
        getContentPane().add(idDonatur);
        idDonatur.setBounds(190, 170, 110, 17);

        tIdDonatur.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tIdDonatur);
        tIdDonatur.setBounds(310, 160, 190, 30);

        namaDonatur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaDonatur.setText("Nama Donatur");
        getContentPane().add(namaDonatur);
        namaDonatur.setBounds(190, 210, 110, 17);

        tNamaDonatur.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tNamaDonatur);
        tNamaDonatur.setBounds(310, 200, 190, 30);

        idPengelola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idPengelola.setText("ID Pengelola");
        getContentPane().add(idPengelola);
        idPengelola.setBounds(190, 250, 140, 17);

        tIdPengelola.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tIdPengelola);
        tIdPengelola.setBounds(310, 240, 190, 30);

        namaPengelola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaPengelola.setText("Nama Pengelola");
        getContentPane().add(namaPengelola);
        namaPengelola.setBounds(540, 90, 120, 17);

        tNamaPengelola.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tNamaPengelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaPengelolaActionPerformed(evt);
            }
        });
        getContentPane().add(tNamaPengelola);
        tNamaPengelola.setBounds(660, 80, 190, 30);

        Jenis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jenis.setText("Jenis Barang");
        getContentPane().add(Jenis);
        Jenis.setBounds(540, 130, 120, 17);

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Pakaian", "Alat Tulis", "Lainnya" }));
        cbJenis.setSelectedItem(Jenis);
        cbJenis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(cbJenis);
        cbJenis.setBounds(660, 130, 190, 30);

        jumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jumlah.setText("Jumlah Barang");
        getContentPane().add(jumlah);
        jumlah.setBounds(540, 190, 110, 17);

        tJumlah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tJumlah);
        tJumlah.setBounds(660, 180, 190, 30);

        ket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ket.setText("Keterangan");
        getContentPane().add(ket);
        ket.setBounds(540, 230, 110, 17);

        tKeterangan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tKeterangan);
        tKeterangan.setBounds(660, 220, 190, 50);

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Tanggal diterima", "ID Donatur", "Nama Donatur", "ID Pengelola", "Nama Pengelola", "Jenis ", "Jumlah", "Keterangan"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 430, 680, 190);

        btnCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnCari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari);
        btnCari.setBounds(830, 390, 40, 30);

        tCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCariKeyPressed(evt);
            }
        });
        getContentPane().add(tCari);
        tCari.setBounds(580, 390, 240, 30);

        data.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        data.setText("Daftar barang yang diterima");
        getContentPane().add(data);
        data.setBounds(190, 370, 250, 20);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Simpan.png"))); // NOI18N
        btnSimpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(230, 300, 100, 40);

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn ubah.png"))); // NOI18N
        btnUbah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah);
        btnUbah.setBounds(360, 300, 100, 40);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Hapus.png"))); // NOI18N
        btnHapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus);
        btnHapus.setBounds(490, 300, 100, 40);

        btnKosong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Kosong.png"))); // NOI18N
        btnKosong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });
        getContentPane().add(btnKosong);
        btnKosong.setBounds(620, 300, 100, 40);

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cetak.png"))); // NOI18N
        btnCetak.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak);
        btnCetak.setBounds(750, 300, 100, 40);

        bg.setBackground(new java.awt.Color(194, 194, 194));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/T_BARANG.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1010, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        new beranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnDonaturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonaturActionPerformed
        // TODO add your handling code here:
        new dataDonatur().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDonaturActionPerformed

    private void btnPengelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengelolaActionPerformed
        // TODO add your handling code here:
        new dataPengelola().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPengelolaActionPerformed

    private void btnSantriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSantriActionPerformed
        // TODO add your handling code here:
        new dataSantri().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSantriActionPerformed

    private void btnDanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanaActionPerformed
        // TODO add your handling code here:
        new masukDana().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDanaActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        new masukBarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengeluaranActionPerformed
        // TODO add your handling code here:
        new pengeluaran().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPengeluaranActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        int bar = tabelBarang.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        tIdBarang.setText(a);
        tTgl.setText(b);
        tIdDonatur.setText(c);
        tNamaDonatur.setText(d);
        tIdPengelola.setText(e);
        tNamaPengelola.setText(f);
        cbJenis.setSelectedItem(g);
        tJumlah.setText(h);
        tKeterangan.setText(i);
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO barang values(?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, tIdBarang.getText());
            stat.setString(2, tTgl.getText());
            stat.setString(3, tIdDonatur.getText());
            stat.setString(4, tNamaDonatur.getText());
            stat.setString(5, tIdPengelola.getText());
            stat.setString(6, tNamaPengelola.getText());
            stat.setString(7, cbJenis.getSelectedItem().toString());
            stat.setString(8, tJumlah.getText());
            stat.setString(9, tKeterangan.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan");
            kosong();
            tIdBarang.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Simpan"+e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="UPDATE barang set IdBarang=?, tgl=?, idDonatur=?, namaDonatur=?,"
                    + "idPengelola=?, namaPengelola=?, jenisBarang=?, jumlahBarang=?,"
                    + " keterangan=? Where IdBarang =  '"+tIdBarang.getText()+"'";
            PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, tIdBarang.getText());
            stat.setString(2, tTgl.getText());
            stat.setString(3, tIdDonatur.getText());
            stat.setString(4, tNamaDonatur.getText());
            stat.setString(5, tIdPengelola.getText());
            stat.setString(6, tNamaPengelola.getText());
            stat.setString(7, cbJenis.getSelectedItem().toString());
            stat.setString(8, tJumlah.getText());
            stat.setString(9, tKeterangan.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil di Ubah");
            kosong();
            tIdBarang.requestFocus();
            datatable();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Gagal di Ubah "+e);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int hapus = JOptionPane.showConfirmDialog(null, "Hapus", "Konfirmasi Dialog",
            JOptionPane.YES_NO_CANCEL_OPTION);
        if(hapus == 0) {
            String sql="DELETE FROM barang Where IdBarang =  '"+tIdBarang.getText()+"'";
            try {
                PreparedStatement stat = con.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
                kosong();
                tIdBarang.requestFocus();
                datatable();
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Data Gagal di Hapus"+e);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        JasperReport reports;
        String path = "C:\\Users\\user\\Documents\\NetBeansProjects\\aplikasi_donatur\\src\\cetakan\\report_barang.jasper";
        try {
            HashMap hash = new HashMap();
            String inputId = JOptionPane.showInputDialog("Masukkan Id Donatur:");
            hash.put("id_donatur", inputId);
         
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, hash, con);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
       
        } catch (JRException ex) {
            Logger.getLogger(masukBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void tNamaPengelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaPengelolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaPengelolaActionPerformed

    private void tIdBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdBarangActionPerformed

    private void tTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTglActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        Object[] Baris={"ID Barang","Tanggal Barang diterima","ID Donatur","Nama Donatur",
            "ID Pengelola","Nama Pengelola","Jenis","Jumlah","Keterangan"};
        tabmode=new DefaultTableModel(null,Baris);
        tabelBarang.setModel(tabmode);
        String sql="SELECT * FROM barang WHERE idBarang LIKE '%"+tCari.getText()+"%'";

        try{
            java.sql.Statement stat=con.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("idBarang");
                String b = hasil.getString("tgl");
                String c = hasil.getString("idDonatur");
                String d = hasil.getString("namaDonatur");
                String e = hasil.getString("idPengelola");
                String f = hasil.getString("namaPengelola");
                String g = hasil.getString("jenisBarang");
                String h = hasil.getString("jumlahBarang");
                String i = hasil.getString("keterangan");
            
                String[] data={a,b,c,d,e,f,g,h,i};
                tabmode.addRow(data);
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_btnCariActionPerformed

    private void tCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyPressed
        // TODO add your handling code here:
//            Object[] Baris={"ID Barang","Tanggal Barang diterima","ID Donatur","Nama Donatur",
//            "ID Pengelola","Nama Pengelola","Jenis","Jumlah","Keterangan"};
//        tabmode=new DefaultTableModel(null,Baris);
//        tabelBarang.setModel(tabmode);
//        String sql="SELECT * FROM barang WHERE idBarang LIKE '%"+tCari.getText()+"%'";
//
//        try{
//            java.sql.Statement stat=con.createStatement();
//            ResultSet hasil=stat.executeQuery(sql);
//            while(hasil.next()){
//                String a = hasil.getString("idBarang");
//                String b = hasil.getString("tgl");
//                String c = hasil.getString("idDonatur");
//                String d = hasil.getString("namaDonatur");
//                String e = hasil.getString("idPengelola");
//                String f = hasil.getString("namaPengelola");
//                String g = hasil.getString("jenisBarang");
//                String h = hasil.getString("jumlahBarang");
//                String i = hasil.getString("keterangan");
//            
//                String[] data={a,b,c,d,e,f,g,h,i};
//                tabmode.addRow(data);
//            }
//        }catch(Exception e){
//            
//        }
    }//GEN-LAST:event_tCariKeyPressed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnKosongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masukBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jenis;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnDana;
    private javax.swing.JButton btnDonatur;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKosong;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPengelola;
    private javax.swing.JButton btnPengeluaran;
    private javax.swing.JButton btnSantri;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JLabel data;
    private javax.swing.JLabel idBarang;
    private javax.swing.JLabel idDonatur;
    private javax.swing.JLabel idPengelola;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel ket;
    private javax.swing.JLabel namaDonatur;
    private javax.swing.JLabel namaPengelola;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tIdBarang;
    private javax.swing.JTextField tIdDonatur;
    private javax.swing.JTextField tIdPengelola;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JTextField tKeterangan;
    private javax.swing.JTextField tNamaDonatur;
    private javax.swing.JTextField tNamaPengelola;
    private javax.swing.JTextField tTgl;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JLabel tglMasuk;
    // End of variables declaration//GEN-END:variables
}
