/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Asus
 */
public class pengeluaran extends javax.swing.JFrame {
    private Connection con = new koneksi().connect();
    private Statement stat;
    private ResultSet res;
    private DefaultTableModel tabmode;

    /**
     * Creates new form pengeluaran
     */
    public pengeluaran() {
        initComponents();
        datatable();
        setLocationRelativeTo(this);
    }

    protected void aktif(){
        tId.setEnabled(true);
        tTgl.setEnabled(true);
        tNominal.setEnabled(true);
        tPj.setEnabled(true);
        tKet.setEnabled(true);
        tId.requestFocus();
    }
    
    protected void kosong() {
        tId.setText("");
        tTgl.setText("");
        tNominal.setText("");
        tPj.setText("");
        tKet.setText("");
    }
    
    protected void datatable() {
        Object[] Baris={"ID Pengeluaran","Tanggal Dana dikeluarkan","Nominal",
            "Penanggung Jawab","Keterangan"};
        tabmode=new DefaultTableModel(null,Baris);
        tabelPengeluaran.setModel(tabmode);
        String sql="SELECT * FROM pengeluaran";
        
        try{
            java.sql.Statement stat=con.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("idPengeluaran");
                String b = hasil.getString("tgl");
                String c = hasil.getString("nominal");
                String d = hasil.getString("pj");
                String e = hasil.getString("keterangan");
            
                String[] data={a,b,c,d,e};
                tabmode.addRow(data);
            }
        }catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        btnDonatur = new javax.swing.JButton();
        btnPengelola = new javax.swing.JButton();
        btnSantri = new javax.swing.JButton();
        btnDana = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnPengeluaran = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        idPengeluaran = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        tglKeluar = new javax.swing.JLabel();
        tTgl = new javax.swing.JTextField();
        nominal = new javax.swing.JLabel();
        tNominal = new javax.swing.JTextField();
        pj = new javax.swing.JLabel();
        tPj = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();
        tKet = new javax.swing.JTextField();
        data = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPengeluaran = new javax.swing.JTable();
        btnCetak = new javax.swing.JButton();
        btnKosong = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(914, 850));
        setMinimumSize(new java.awt.Dimension(914, 690));
        getContentPane().setLayout(null);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnMenu.png"))); // NOI18N
        btnMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(0, 60, 170, 50);

        btnDonatur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnDonatur.png"))); // NOI18N
        btnDonatur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDonatur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonaturActionPerformed(evt);
            }
        });
        getContentPane().add(btnDonatur);
        btnDonatur.setBounds(0, 110, 170, 50);

        btnPengelola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnPengelola.png"))); // NOI18N
        btnPengelola.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPengelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengelolaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengelola);
        btnPengelola.setBounds(0, 160, 170, 50);

        btnSantri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnSantri.png"))); // NOI18N
        btnSantri.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSantri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSantriActionPerformed(evt);
            }
        });
        getContentPane().add(btnSantri);
        btnSantri.setBounds(0, 210, 170, 50);

        btnDana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnDana.png"))); // NOI18N
        btnDana.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDana);
        btnDana.setBounds(0, 260, 170, 50);

        btnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - btnBarang.png"))); // NOI18N
        btnBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnBarang);
        btnBarang.setBounds(0, 310, 170, 50);

        btnPengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiri - bold - btnPengeluaran.png"))); // NOI18N
        btnPengeluaran.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengeluaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengeluaran);
        btnPengeluaran.setBounds(0, 360, 170, 50);

        Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Keluar.png"))); // NOI18N
        Keluar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(10, 570, 150, 40);

        idPengeluaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idPengeluaran.setText("ID Pengeluaran");
        getContentPane().add(idPengeluaran);
        idPengeluaran.setBounds(220, 100, 110, 17);

        tId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tId);
        tId.setBounds(400, 90, 290, 30);

        tglKeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tglKeluar.setText("Tanggal Dana dikeluarkan");
        getContentPane().add(tglKeluar);
        tglKeluar.setBounds(220, 140, 160, 17);

        tTgl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tTgl);
        tTgl.setBounds(400, 130, 290, 30);

        nominal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nominal.setText("Nominal");
        getContentPane().add(nominal);
        nominal.setBounds(220, 180, 110, 17);

        tNominal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tNominal);
        tNominal.setBounds(400, 170, 290, 30);

        pj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pj.setText("Penanggung Jawab");
        getContentPane().add(pj);
        pj.setBounds(220, 220, 150, 17);

        tPj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tPj);
        tPj.setBounds(400, 210, 290, 30);

        ket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ket.setText("Keterangan");
        getContentPane().add(ket);
        ket.setBounds(220, 260, 110, 17);

        tKet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tKet);
        tKet.setBounds(400, 250, 290, 60);

        data.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        data.setText("Data Pengeluaran");
        getContentPane().add(data);
        data.setBounds(200, 360, 190, 20);

        btnCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnCari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari);
        btnCari.setBounds(810, 390, 40, 30);

        tCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCariKeyPressed(evt);
            }
        });
        getContentPane().add(tCari);
        tCari.setBounds(560, 390, 240, 30);

        tabelPengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pengeluaran", "Tanggal Dana dikeluarkan", "Nominal", "Penanggung Jawab", "Keterangan"
            }
        ));
        tabelPengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPengeluaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPengeluaran);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 430, 670, 200);

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cetak.png"))); // NOI18N
        btnCetak.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak);
        btnCetak.setBounds(750, 320, 100, 40);

        btnKosong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Kosong.png"))); // NOI18N
        btnKosong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });
        getContentPane().add(btnKosong);
        btnKosong.setBounds(750, 260, 100, 40);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Hapus.png"))); // NOI18N
        btnHapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus);
        btnHapus.setBounds(750, 200, 100, 40);

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn ubah.png"))); // NOI18N
        btnUbah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah);
        btnUbah.setBounds(750, 140, 100, 40);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn Simpan.png"))); // NOI18N
        btnSimpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(750, 80, 100, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/T_PENGELUARAN.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 914, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        new beranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnDonaturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonaturActionPerformed
        // TODO add your handling code here:
        new dataDonatur().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDonaturActionPerformed

    private void btnPengelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengelolaActionPerformed
        // TODO add your handling code here:
        new dataPengelola().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPengelolaActionPerformed

    private void btnSantriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSantriActionPerformed
        // TODO add your handling code here:
        new dataSantri().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSantriActionPerformed

    private void btnDanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanaActionPerformed
        // TODO add your handling code here:
        new masukDana().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDanaActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        new masukBarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengeluaranActionPerformed
        // TODO add your handling code here:
        new pengeluaran().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPengeluaranActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    private void tabelPengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPengeluaranMouseClicked
        // TODO add your handling code here:
        int bar = tabelPengeluaran.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();

        tId.setText(a);
        tTgl.setText(b);
        tNominal.setText(c);
        tPj.setText(d);
        tKet.setText(e);
    }//GEN-LAST:event_tabelPengeluaranMouseClicked

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        JasperReport reports;
        String path = "C:\\Users\\user\\Documents\\NetBeansProjects\\aplikasi_donatur\\src\\cetakan\\report_luaran.jasper";
        try {
            reports = (JasperReport) net.sf.jasperreports.engine.util.JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, con);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(masukBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int hapus = JOptionPane.showConfirmDialog(null,"Hapus", "Konfirmasi Dialog",
            JOptionPane.YES_NO_CANCEL_OPTION);
        if(hapus == 0) {
            String sql="DELETE FROM pengeluaran Where IdPengeluaran =  '"+tId.getText()+"'";
            try {
                PreparedStatement stat = con.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
                kosong();
                tId.requestFocus();
                datatable();
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Data Gagal di Hapus"+e);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="UPDATE pengeluaran set IdPengeluaran=?, tgl=?, nominal=?, pj=?, "
            + "keterangan=? WHERE IdPengeluaran =  '"+tId.getText()+"'";
            PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, tId.getText());
            stat.setString(2, tTgl.getText());
            stat.setString(3, tNominal.getText());
            stat.setString(4, tPj.getText());
            stat.setString(5, tKet.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil di Ubah");
            kosong();
            tId.requestFocus();
            datatable();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Gagal di Ubah "+e);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO pengeluaran values(?,?,?,?,?)";
        try {
            PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, tId.getText());
            stat.setString(2, tTgl.getText());
            stat.setString(3, tNominal.getText());
            stat.setString(4, tPj.getText());
            stat.setString(5, tKet.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan");
            kosong();
            tId.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Simpan"+e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        Object[] Baris={"ID Pengeluaran","Tanggal Dana dikeluarkan","Nominal",
            "Penanggung Jawab","Keterangan"};
        tabmode=new DefaultTableModel(null,Baris);
        tabelPengeluaran.setModel(tabmode);
        String sql="SELECT * FROM pengeluaran WHERE idPengeluaran LIKE '%"+tCari.getText()+"%'";
        
        try{
            java.sql.Statement stat=con.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("idPengeluaran");
                String b = hasil.getString("tgl");
                String c = hasil.getString("nominal");
                String d = hasil.getString("pj");
                String e = hasil.getString("keterangan");
            
                String[] data={a,b,c,d,e};
                tabmode.addRow(data);
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void tCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyPressed
        //         TODO add your handling code here:
        //        Object[] Baris={"ID Dana","Tanggal Dana diterima","ID Pengelola","Nama Pengelola",
            //            "ID Donatur","Nama Donatur","Nominal","Bentuk","Keterangan"};
        //        tabmode=new DefaultTableModel(null,Baris);
        //        tabelDana.setModel(tabmode);
        //        String sql="SELECT * FROM dana WHERE idDana LIKE '%"+tCari.getText()+"%'";
        //
        //
        //        try{
            //            java.sql.Statement stat=con.createStatement();
            //            ResultSet hasil=stat.executeQuery(sql);
            //            while(hasil.next()){
                //                String a = hasil.getString("idDana");
                //                String b = hasil.getString("tgl");
                //                String c = hasil.getString("idPengelola");
                //                String d = hasil.getString("namaPengelola");
                //                String e = hasil.getString("idDonatur");
                //                String f = hasil.getString("namaDonatur");
                //                String g = hasil.getString("nominal");
                //                String h = hasil.getString("bentuk");
                //                String i = hasil.getString("keterangan");
                //
                //                String[] data={a,b,c,d,e,f,g,h,i};
                //                tabmode.addRow(data);
                //            }
            //        }catch(Exception e){
            //
            //        }
    }//GEN-LAST:event_tCariKeyPressed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnKosongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnDana;
    private javax.swing.JButton btnDonatur;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKosong;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPengelola;
    private javax.swing.JButton btnPengeluaran;
    private javax.swing.JButton btnSantri;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel data;
    private javax.swing.JLabel idPengeluaran;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ket;
    private javax.swing.JLabel nominal;
    private javax.swing.JLabel pj;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tKet;
    private javax.swing.JTextField tNominal;
    private javax.swing.JTextField tPj;
    private javax.swing.JTextField tTgl;
    private javax.swing.JTable tabelPengeluaran;
    private javax.swing.JLabel tglKeluar;
    // End of variables declaration//GEN-END:variables
}
